#:kivy 2.3.0
<Button>:
    size_hint: 0.2,0.2
<MainWindow>:
    Button:
        text: "Button 1"
        pos_hint: {"x":0,"y":0}

    Button:
        text: "Button 2"
        pos_hint: {"x":0,"right":1}
    
    Button:
        text: "Button 3"
        pos_hint: {"center_x":0.5,"center_y":0.5}

    Button:
        text: "Button 4"
        pos_hint: {"left":1,"top":1}

    Button:
        text: "Button 5"
        pos_hint: {"right":1,"top":1}